#Publish all joint states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Joint trajectory controller
joint_trajectory_controller:
  type: "velocity_controllers/JointTrajectoryController"
  joints:
    - slew
    - boom_1
    - boom_2
  gains:
    slew: { p: 100, d: 1, i: 1, i_clamp: 1 }
    boom_1: { p: 100, d: 1, i: 1, i_clamp: 1 }
    boom_2: { p: 100, d: 1, i: 1, i_clamp: 1 }
  velocity_ff:
    slew: 1.0
    boom_1: 1.0
    boom_2: 1.0
  state_publish_rate: 50
  action_monitor_rate: 20 
