#Publish all joint states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Joint trajectory controller
joint_trajectory_controller:
  type: "velocity_controllers/JointTrajectoryController"
  joints:
    - joint1
    - joint2
    - joint3
  gains:
    joint1: { p: 100, d: 0.01, i: 10.0 }
    joint2: { p: 100, d: 0.01, i: 10.0 }
    joint3: { p: 100, d: 0.01, i: 10.0 }
  state_publish_rate: 50
  action_monitor_rate: 20 