#!/usr/bin/env python

import time
import numpy as np

from threading import Lock

import rospy
from sensor_msgs.msg import JointState

from crane_msgs.msg import CraneControl
from crane_pendulum_dynamics.rk4 import rk4
from crane_pendulum_dynamics.spherical_pendulum import spherical_pendulum_dyn


class SphericalPendulumVisualization(object):
    def __init__(self):
        self._joint_state_pub = rospy.Publisher(
            'pendulum_joint_states', JointState, queue_size=5)

        self._command_sub = rospy.Subscriber(
            '/lyapunov_pendulum_damping_controller/commanded', CraneControl, callback=self._command_cb)

        self._command = np.array([0.0, 0.0])

        self._command_lock = Lock()

    def _command_cb(self, msg):
        self._command_lock.acquire()
        self._command = np.array([msg.gx, msg.gy])
        self._command_lock.release()

    def run(self):

        q = np.deg2rad([5.0, 0.0, 5.0, 0.0])

        start_time = time.time()
        current_time = start_time
        previous_time = current_time

        rate = rospy.Rate(100)
        while not rospy.is_shutdown():

            current_time = time.time()
            dt = current_time - previous_time
            previous_time = current_time

            # update the time and state

            self._command_lock.acquire()
            (t, q) = rk4(current_time, q, dt, spherical_pendulum_dyn, self._command)
            self._command_lock.release()

            msg = JointState()
            msg.header.stamp = rospy.Time.now()
            msg.name.append("phix_joint")
            msg.position.append(q[0])
            msg.velocity.append(q[1])
            msg.name.append("phiy_joint")
            msg.position.append(q[2])
            msg.velocity.append(q[3])
            self._joint_state_pub.publish(msg)

            rate.sleep()


if __name__ == '__main__':
    try:
        rospy.init_node('spherical_pendulum_visualizer')
        spv = SphericalPendulumVisualization()
        spv.run()

    except rospy.ROSInterruptException:
        pass
