#!/usr/bin/env python

import rospy
import message_filters
from sensor_msgs.msg import Image, CameraInfo

pub = rospy.Publisher(
    'republish', Image, queue_size=3)

def callback(image0, image1, image2):
rospy.loginfo('callback')
    pub.publish(image0)


rospy.init_node('crane_vision_sync')

camera0_sub = message_filters.Subscriber('/camera0/image_raw', Image)
camera1_sub = message_filters.Subscriber('/camera1/image_raw', Image)
camera2_sub = message_filters.Subscriber('/camera2/image_raw', Image)

ts = message_filters.TimeSynchronizer([camera0_sub, camera1_sub, camera2_sub], 10)
ts.registerCallback(callback)
rospy.spin()


    

